{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastchat-helm.fullname" . }}-api
  labels:
    {{- include "fastchat-helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: fastchat-api
{{- end }}