{{- if .Values.controller.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastchat-helm.fullname" . }}-controller
  labels:
    {{- include "fastchat-helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: controller
    port: 21001
    targetPort: 21001
    protocol: TCP
  selector:
    app: fastchat-controller
    {{- include "fastchat-helm.selectorLabels" . | nindent 4 }}
{{- end }}
