{{- if .Values.webserver.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fastchat-helm.fullname" . }}-web-server
  labels:
  {{- include "fastchat-helm.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.webserver.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "fastchat-helm.fullname" . }}-web-server'
            port:
              number: 8000
        path: /
        pathType: Prefix
{{- end }}