{{- if .Values.webserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastchat-helm.fullname" . }}-web-server
  labels:
    {{- include "fastchat-helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: fastchat-web-server
    {{- include "fastchat-helm.selectorLabels" . | nindent 4 }}
  ports:
  - name: web-server
    port: 8000
    targetPort: 8000
    protocol: TCP
{{- end }}
